# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#Demo for WWWC Codes Medellin
#DevOps Fundamentals

trigger:
- master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: compile-template.yml  # Template reference
    - template: quality-check.yml 
    - template: unit-test-check.yml
    - template: docker-build.yml