# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  sonarCloudEndpointName: 'SC'
  sonarCloudOrganization: 'karsegri'
  sonarCloudProjectKey: 'karsegri_pocsharedpipelines'
  sonarCloudProjectName: 'pocsharedpipelines'

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: compile-template.yml  # Template reference
    - template: quality-check.yml 